services:
  smarthome-hub:
    build: .
    image: ilyamatsuev/smarthome-hub-server
    container_name: smarthome-hub
    restart: always
    ports:
      - "${PORT}:3000"
    volumes:
      - ./.env:/usr/src/app/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mongodb
      - mqtt-broker
    networks:
      - smarthome-network

  mongodb:
    image: mongo:7.0.16-jammy
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data/${NODE_ENV:-local}/:/data/db
    networks:
      - smarthome-network

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    restart: unless-stopped
    tty: true
    ports:
      - "${MQTT_PORT}:1885"
    volumes:
      - ./configs/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./configs/mqtt/pwfile:/mosquitto/config/pwfile:rw
    networks:
      - smarthome-network

  # TODO: Need to print a warning message or something, if z2m is not working on the host
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - ./configs/zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml
      - /run/udev:/run/udev:ro
    devices:
      - ${ZIGBEE_DONGLE_PATH}:/dev/ttyACM0
    ports:
      - "${Z2M_FRONT_END_PORT}:8080"
    depends_on:
      - mqtt-broker
    networks:
      - smarthome-network

  smarthome-image-watcher:
    image: ghcr.io/nicholas-fedor/watchtower:latest
    container_name: smarthome-image-watcher
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 0 * * * *
      - WATCHTOWER_CLEANUP=true
    network_mode: host

  smarthome-image-watcher-once:
    image: ghcr.io/nicholas-fedor/watchtower:latest
    container_name: smarthome-image-watcher-once
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_CLEANUP=true
    network_mode: host

networks:
  smarthome-network:
    driver: bridge
