services:
  smarthome-hub-server-prod:
    image: ilyamatsuev/smarthome-hub-server
    container_name: smarthome-hub-server-prod
    env_file: .env.prod
    restart: always
    volumes:
      - ./.env.prod:/usr/src/app/.env.prod
    expose:
      - "3020"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: host

  mongodb-prod:
    image: mongo:7.0.16-jammy
    container_name: mongodb-prod
    env_file: .env.prod
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - ./data/prod/:/data/db
    networks:
      - smarthome-network

  mqtt-broker-prod:
    image: eclipse-mosquitto
    container_name: mqtt-broker-prod
    env_file: .env.prod
    restart: always
    tty: true
    ports:
      - "1885:1885"
    volumes:
      - ./configs/mqtt/mosquitto.prod.conf:/mosquitto/config/mosquitto.conf:rw
      - ./configs/mqtt/pwfile.prod:/mosquitto/config/pwfile:rw
    networks:
      - smarthome-network

  smarthome-image-watcher:
    image: containrrr/watchtower:latest
    container_name: smarthome-image-watcher
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 0 * * * *
      - WATCHTOWER_CLEANUP=true

  smarthome-image-watcher-once:
    image: containrrr/watchtower:latest
    container_name: smarthome-image-watcher-once
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_CLEANUP=true

networks:
  smarthome-network:
    driver: bridge
