services:
  smarthome-hub:
    build: .
    image: ilyamatsuev/smarthome-hub-server
    container_name: smarthome-hub
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mongodb
      - mqtt-broker
    network_mode: host

  mongodb:
    image: mongo:7.0.16-jammy
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/${NODE_ENV:-local}/:/data/db
    networks:
      - smarthome-network

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    restart: unless-stopped
    tty: true
    ports:
      - "1885:1885"
    volumes:
      - ./configs/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./configs/mqtt/pwfile:/mosquitto/config/pwfile:rw
    networks:
      - smarthome-network

  smarthome-image-watcher:
    image: ghcr.io/nicholas-fedor/watchtower:latest
    container_name: smarthome-image-watcher
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 0 * * * *
      - WATCHTOWER_CLEANUP=true
    network_mode: host

  smarthome-image-watcher-once:
    image: ghcr.io/nicholas-fedor/watchtower:latest
    container_name: smarthome-image-watcher-once
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_CLEANUP=true
    network_mode: host

networks:
  smarthome-network:
    driver: bridge
