export const DEVICES_CONTROL_FACTORY_PROVIDER = 'DEVICES_CONTROL_FACTORY';
export const DEVICE_TRANSPORT_FACTORY_PROVIDER = 'DEVICE_TRANSPORT_PROVIDER';

export const TUYA_DEVICE_MIN_BRIGHTNESS = 1;
export const TUYA_DEVICE_MAX_BRIGHTNESS = 100;
