export const DEVICE_MODEL_PROVIDER_NAME = 'DEVICE_MODEL';
export const DEVICE_SCHEMA_NAME = 'Device';

export const DEVICE_NAME_MIN_LENGTH = 3;
export const DEVICE_NAME_MAX_LENGTH = 40;
export const DEVICE_DEFAULT_UPDATE_INTERVAL = 0;
export const DEVICE_ALLOWED_IP_VERSION = 4;

export const MIN_PAIRING_TIMEOUT_SECONDS = 30;
export const MAX_PAIRING_TIMEOUT_SECONDS = 254;
