export const USER_MODEL_PROVIDER_NAME = 'USER_MODEL';
export const USER_SCHEMA_NAME = 'User';

export const USER_PASSWORD_MIN_LENGTH = 4;
export const USER_PASSWORD_MAX_LENGTH = 20;

export const REGISTRATION_REQUEST_MODEL_PROVIDER_NAME = 'REGISTRATION_REQUEST_MODEL';
export const REGISTRATION_REQUEST_SCHEMA_NAME = 'RegistrationRequest';

export const REGISTRATION_REQUEST_DEFAULT_BLACK_LISTED = false;
export const REGISTRATION_REQUEST_COMMENT_MAX_LENGTH = 100;
export const REGISTRATION_REQUEST_TOTP_AUTO_APPROVAL_COMMENT = 'Automatically approved via TOTP';
