fans:
  mqtt:
    controls:
      - label: "On"
        name: "on"
        type: boolean
        description: "Switch on/off state"
      - label: "Speed levels"
        name: "speedLevels"
        type: object
        description: "Temperature thresholds the fan speed levels switch at. The structure is validated by the ESP32 fans DTO"
    measurements:
      - label: "Temperature (C)"
        name: "temperature"
        type: number
        description: "Air temperature around the device in Celsius"
      - label: "Fan Speed (%)"
        name: "speedPercentage"
        type: number
        description: "How fast the fans spin based on the temperature level"
        constraints:
          min: 0
          max: 100

lock:
  mqtt:
    controls:
      - label: "On"
        name: "on"
        type: boolean
        description: "Switch on/off state"
      - label: "Is unlocked?"
        name: "unlocked"
        type: boolean
        description: "When set to true, the lock becomes unlocked for the time specified in the unlock timeout"
        default: false
      - label: "Unlock timeout (ms)"
        name: "unlockTimeoutMs"
        type: number
        description: "Determines the amount of time (in milliseconds) the lock remains unlocked"
        default: 5000
        constraints:
          min: 1000
          max: 60000
