plug:
  http:
    controls:
      - label: "On"
        name: "on"
        type: boolean
        description: "Switch on/off state"
    measurements:
      - label: "Voltage"
        name: "voltage"
        type: number
        description: "The currently consumed voltage (volts) while the device is on"
      - label: "Current"
        name: "current"
        type: number
        description: "The currently consumed current (amperes) while the device is on"
      - label: "Power"
        name: "power"
        type: number
        description: "The currently consumed power (watts) while the device is on"
        path: "apower"

switch:
  http:
    controls:
      - label: "On"
        name: "on"
        type: boolean
        description: "Switch on/off state"
    measurements:
      - label: "Voltage"
        name: "voltage"
        type: number
        description: "The currently consumed voltage (volts) while the device is on"
      - label: "Current"
        name: "current"
        type: number
        description: "The currently consumed current (amperes) while the device is on"
      - label: "Power"
        name: "power"
        type: number
        description: "The currently consumed power (watts) while the device is on"
        path: "apower"
