version: "3.8"
services:
  mongodb-prod:
    image: mongo:7.0.16-jammy
    container_name: mongodb-prod
    env_file: .env.prod
    restart: always
    ports:
      - "27019:27019"
    networks:
      - smarthome-network

  mqtt-broker-prod:
    image: eclipse-mosquitto
    container_name: mqtt-broker-prod
    env_file: .env.prod
    restart: always
    tty: true
    ports:
      - "1885:1885"
    volumes:
      - ./mqtt/mosquitto.prod.conf:/mosquitto/config/mosquitto.conf:rw
    networks:
      - smarthome-network

  smarthome-hub-server-prod:
    image: ilyamatsuev/smarthome-hub-server
    container_name: smarthome-hub-server-prod
    env_file: .env.prod
    restart: always
    ports:
      - "3020:3020"
    expose:
      - "3020"
    networks:
      - smarthome-network

  smarthome-hub-server-image-watcher:
    image: containrrr/watchtower:latest
    container_name: smarthome-hub-server-image-watcher
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_SCHEDULE=0 0 * * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DISABLE_CONTAINERS=mongodb-prod,mongodb-test,mongodb

  smarthome-hub-server-image-watcher-once:
    image: containrrr/watchtower:latest
    container_name: smarthome-hub-server-image-watcher-once
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DISABLE_CONTAINERS=mongodb-prod,mongodb-test,mongodb,mqtt-broker,mqtt-broker-test,mqtt-broker-prod

networks:
  smarthome-network:
    driver: bridge
