version: "3.8"
services:
  mongodb:
    image: mongo:7.0.16-jammy
    container_name: mongodb
    env_file: .env.local
    ports:
      - "27017:27017"
    networks:
      - smarthome-network

  # Can be tested using an online client https://testclient-cloud.mqtt.cool/
  # To crete a new user for a container:
  #   docker exec -it mqtt-broker sh
  #   mosquitto_passwd -c /mosquitto/config/pwfile <username>
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    restart: always
    tty: true
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt:/mosquitto/config:rw
    networks:
      - smarthome-network

  smarthome-hub-server:
    build: .
    image: ilyamatsuev/smarthome-hub-server
    container_name: smarthome-hub-server
    env_file: .env.local
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - smarthome-network

networks:
  smarthome-network:
    driver: bridge
