version: "3.8"
services:
  mongodb:
    image: mongo:7.0.16-jammy
    container_name: mongodb-test
    env_file: .env.test
    ports:
      - "27017:27017"
    networks:
      - smarthome-network

  smarthome-hub-server:
    image: smarthome-hub-server
    container_name: smarthome-hub-server-test
    env_file: .env.test
    ports:
      - "3000:3000"
    networks:
      - smarthome-network

networks:
  smarthome-network:
    driver: bridge
