version: "3.8"
services:
  mongodb-prod:
    image: mongo:7.0.16-jammy
    container_name: mongodb-prod
    env_file: .env.prod
    restart: always
    ports:
      - "27019:27019"
    networks:
      - smarthome-network

  smarthome-hub-server-prod:
    image: ilyamatsuev/smarthome-hub-server
    container_name: smarthome-hub-server-prod
    env_file: .env.prod
    restart: always
    ports:
      - "3020:3020"
    expose:
      - "3020"
    networks:
      - smarthome-network

  smarthome-hub-server-image-watcher:
    image: crazymax/diun:latest
    container_name: smarthome-hub-server-image-watcher
    restart: always
    volumes:
      - ./diun.yaml:/app/diun.yaml
      - ./scripts/restart-hub.sh:/app/restart-hub.sh
      - /var/run/docker.sock:/var/run/docker.sock
    command: start
    environment:
      - DIUN_LOG_LEVEL=info

networks:
  smarthome-network:
    driver: bridge
