services:
  smarthome-hub-server-test:
    image: ilyamatsuev/smarthome-hub-server
    container_name: smarthome-hub-server-test
    env_file: .env.test
    restart: always
    ports:
      - "3010:3010"
    volumes:
      - ./.env.test:/usr/src/app/.env.test
    expose:
      - "3010"
    network_mode: host

  mongodb-test:
    image: mongo:7.0.16-jammy
    container_name: mongodb-test
    env_file: .env.test
    restart: always
    ports:
      - "27018:27017"
    networks:
      - smarthome-network

  mqtt-broker-test:
    image: eclipse-mosquitto
    container_name: mqtt-broker-test
    env_file: .env.test
    restart: always
    tty: true
    ports:
      - "1884:1884"
    volumes:
      - ./mqtt/mosquitto.test.conf:/mosquitto/config/mosquitto.conf:rw
      - ./mqtt/pwfile.test:/mosquitto/config/pwfile:rw
    networks:
      - smarthome-network

networks:
  smarthome-network:
    driver: bridge
