version: "3.8"
services:
  mongodb:
    image: mongo:7.0.16-jammy
    container_name: mongodb
    env_file: .env.local
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - smarthome-network

  smarthome-hub-server:
    build: .
    image: smarthome-hub-server
    container_name: smarthome-hub-server
    env_file: .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    networks:
      - smarthome-network

volumes:
  dbdata6:

networks:
  smarthome-network:
    driver: bridge
