services:
  mongodb:
    image: mongo:7.0.16-jammy
    container_name: mongodb
    env_file: .env.local
    ports:
      - "27017:27017"
    networks:
      - smarthome-network

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    env_file: .env.local
    restart: always
    tty: true
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto.local.conf:/mosquitto/config/mosquitto.conf:rw
      - ./mqtt/pwfile.local:/mosquitto/config/pwfile:rw
    networks:
      - smarthome-network

  smarthome-hub-server:
    build: .
    image: ilyamatsuev/smarthome-hub-server
    container_name: smarthome-hub-server
    env_file: .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./.env.local:/usr/src/app/.env.local
    expose:
      - "3000"
    networks:
      - smarthome-network

networks:
  smarthome-network:
    driver: bridge
