export const REGISTRATION_REQUEST_MODEL_PROVIDER_NAME = 'REGISTRATION_REQUEST_MODEL';
export const REGISTRATION_REQUEST_SCHEMA_NAME = 'RegistrationRequest';

export const REGISTRATION_REQUEST_COMMENT_MAX_LENGTH = 100;
export const REGISTRATION_REQUEST_TOTP_AUTO_APPROVAL_COMMENT = 'Automatically approved via TOTP';
